url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Î 4" # the name of your site, e.g. ACME Corp.

css_dir: "assets/css"

plugins:
  - jekyll-postcss

exclude:
  - node_modules/
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - package.lock

postcss:
  cache: false
